// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwa6Rm7AMa_ZlG4APIWoY4pAg2A2SYyKw',
    appId: '1:530498810284:web:eb9bba179e3a4fd3d18a09',
    messagingSenderId: '530498810284',
    projectId: 'velveta-d417c',
    authDomain: 'velveta-d417c.firebaseapp.com',
    storageBucket: 'velveta-d417c.firebasestorage.app',
    measurementId: 'G-5K1DLQ7QL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sc949uBFhEP9kGKGF5E98Bvq6WrzTsg',
    appId: '1:530498810284:android:d2c8e728f9e41310d18a09',
    messagingSenderId: '530498810284',
    projectId: 'velveta-d417c',
    storageBucket: 'velveta-d417c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuOBzRfR5Mxcw6iFsqFzSKwVFxkEs0qKs',
    appId: '1:530498810284:ios:6e21adf0ae642c8ad18a09',
    messagingSenderId: '530498810284',
    projectId: 'velveta-d417c',
    storageBucket: 'velveta-d417c.firebasestorage.app',
    iosBundleId: 'com.example.velveta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuOBzRfR5Mxcw6iFsqFzSKwVFxkEs0qKs',
    appId: '1:530498810284:ios:6e21adf0ae642c8ad18a09',
    messagingSenderId: '530498810284',
    projectId: 'velveta-d417c',
    storageBucket: 'velveta-d417c.firebasestorage.app',
    iosBundleId: 'com.example.velveta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwa6Rm7AMa_ZlG4APIWoY4pAg2A2SYyKw',
    appId: '1:530498810284:web:5326006867e1e27bd18a09',
    messagingSenderId: '530498810284',
    projectId: 'velveta-d417c',
    authDomain: 'velveta-d417c.firebaseapp.com',
    storageBucket: 'velveta-d417c.firebasestorage.app',
    measurementId: 'G-J0S9VVKC62',
  );
}
